apiVersion: v1
kind: Service
metadata:
  name: {{ include "biomed-mammal-serve.fullname" . }}-backend
  labels:
    app: backend
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
    - name: http
      port: {{ .Values.service.backendPort }}
      targetPort: {{ .Values.service.backendTargetPort }}
      protocol: TCP
