FROM nginx:alpine
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY index.html /usr/share/nginx/html/index.html
COPY attendee.html /usr/share/nginx/html/attendee.html
COPY frontend /usr/share/nginx/html/frontend
COPY pcm-worklet.js /usr/share/nginx/html/pcm-worklet.js
COPY logo.jpg /usr/share/nginx/html/logo.jpg

EXPOSE 80
