apiVersion: v1
kind: Pod
metadata:
  name: vision-app-demo
  labels:
    app: vision-app-demo
spec:
  containers:
    - name: gradio
      image: erdincka/vision_analytics_demo:latest
      ports:
        - containerPort: 7860
      resources:
        requests:
          cpu: "4"
          memory: "10Gi"
        limits:
          cpu: "4"
          memory: "10Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: vision-app-service
spec:
  selector:
    app: vision-app-demo
  ports:
    - protocol: TCP
      port: 7860
      targetPort: 7860
# ---
# apiVersion: networking.istio.io/v1beta1
# kind: VirtualService
# metadata:
#   name: gradio-stream-virtualservice
#   namespace: demo
# spec:
#   hosts:
#     - vision-app.ingress.pcai0109.sv11.hpecolo.net
#   gateways:
#     - istio-system/ezaf-gateway
#   http:
#     - match:
#         - uri:
#             prefix: /
#       rewrite:
#         uri: /
#       route:
#         - destination:
#             host: vision-app-service.demo.svc.cluster.local
#             port:
#               number: 7860
