apiVersion: v1
kind: Service
metadata:
  name: {{ include "protein-binder-design.fullname" . }}-frontend
  labels:
    app: frontend
spec:
  type: ClusterIP
  selector:
    app: frontend
  ports:
    - name: http
      port: {{ .Values.service.frontendPort }}
      targetPort: {{ .Values.service.frontendTargetPort }}
      protocol: TCP
