apiVersion: v1
kind: Secret
metadata:
  name: {{ include "protein-binder-design.fullname" . }}-nvapi
  labels:
    app: frontend
type: Opaque
stringData:
  apiKey: {{ .Values.nvidia.apiKey | quote }}
