apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.deployment.name }}-data
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.deployment.appName }}
  annotations:
    "helm.sh/resource-policy": keep
spec:
  accessModes: [{{ .Values.persistence.data.accessMode }}]
  {{- if .Values.persistence.data.storageClass }}
  storageClassName: {{ .Values.persistence.data.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.data.size }}
