---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.deployment.name }}-api
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.deployment.appName }}
spec:
  type: {{ .Values.service.api.type }}
  ports:
    - name: http
      port: {{ .Values.service.api.port }}
      targetPort: http
  selector:
    app: {{ .Values.deployment.appName }}
---
{{- if .Values.mcp.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.deployment.name }}-mcp
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.deployment.appName }}
spec:
  type: {{ .Values.service.mcp.type }}
  ports:
    - name: mcp
      port: {{ .Values.mcp.port }}
      targetPort: mcp
  selector:
    app: {{ .Values.deployment.appName }}
{{- end }}
