apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "gradio-vlm-chart.fullname" . }}-shared-pv
  labels:
    {{- include "gradio-vlm-chart.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.storage.shared.storageClassName }}
  volumeMode: Filesystem
  {{- $sourcePV := lookup "v1" "PersistentVolume" "" "ezpresto-shared-pv" }}
  # Dynamically copied from ezpresto-shared-pv
  capacity:
    {{- toYaml $sourcePV.spec.capacity | nindent 4 }}
  csi:
    {{- toYaml $sourcePV.spec.csi | nindent 4 }}
  mountOptions:
    {{- toYaml $sourcePV.spec.mountOptions | nindent 4 }}

