apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "gradio-vlm-chart.fullname" . }}-shared-pvc
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gradio-vlm-chart.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: {{ .Values.storage.shared.capacity }}
  storageClassName: {{ .Values.storage.shared.storageClassName }}
  volumeName: {{ include "gradio-vlm-chart.fullname" . }}-shared-pv
  volumeMode: Filesystem
