apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-data
  namespace: {{ .Release.Namespace }}
  labels:
    app: app-data
    {{- include "defence-ops.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
